[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "signata-docs"
authors = [{name = "Congruent Labs", email = "sales@congruentlabs.co"}]
dynamic = ["version", "description"]
